### ISSUE TITLE
empty bucket list

### ISSUE THREAD

**Issue by nadluru** [muschellij2/neurohcp#1]
Dear John,
 
Thank you for writing neurohcp and making it available. I have tried to follow the steps on your vignette https://cran.r-project.org/web/packages/neurohcp/vignettes/hcp.html.
 
I am getting an empty data frame when I do neurohcp::bucketlist(). I have the S3 access enabled and have the access key and the secret key which I used. Still I am getting an empty data frame. Are there any usual pitfalls I might be running into? I do have the latest R (R 3.4.4).
 
Could you please help me solve this issue?
 
Thank you so much for your help.
Best regards,
Nagesh

**Comment by muschellij2** [comment]
This `HCP/100206/T1w/Diffusion` folder doesn't exist in that bucket.  I think you mean `HCP_1200/100206/T1w/Diffusion`.  Also, you need the `/` at the end for that folder only:
```r
download_hcp_dir('HCP_1200/100206/T1w/Diffusion/', verbose = TRUE)
```

**Comment by nadluru** [comment]
I still get the following.

>> r = download_hcp_dir('HCP_1200/100206/T1w/Diffusion/', verbose = TRUE)
URL sent to GET
https://s3.amazonaws.com/hcp-openaccess/?AWSAccessKeyId=accesskey&Expires=1522965574&Signature=BAyr2HiNbz4vCtfsPSEgn3P30ek%3D&prefix=HCP_1200/100206/T1w/Diffusion/&delimiter=
Error in sub(pref, "", res$Key, fixed = TRUE) : 
  invalid 'pattern' argument

**Comment by muschellij2** [comment]
Can you install the dev version of neurohcp:

devtools::install_github("muschelli2j/neurohcp")

then rerun

John

**Comment by nadluru** [comment]
I wasn't able to install the dev version!

>devtools::install_github("muschelli2j/neurohcp")
Downloading GitHub repo muschelli2j/neurohcp@master
from URL https://api.github.com/repos/muschelli2j/neurohcp/zipball/master
Installation failed: Not Found (404)

**Comment by muschellij2** [comment]
`devtools::install_github("muschellij2/neurohcp")`

**Comment by nadluru** [comment]
The dev version seems to be working. I was able to download a sample hcp dir using the `download_hcp_dir` command but the `neurohcp::bucketlist()` still returns empty data frame.
