### ISSUE TITLE
AWS bucket temporary change

### ISSUE THREAD

**Issue by brissend** [muschellij2/neurohcp#2]
The AWS bucket for HCP data has temporarily changed from s3://hcp-openaccess/ to s3://hcp-openaccess-temp/. Is there a way to specify the bucket when downloading a directory/file rather than defaulting to 'hcp-openaccess'?

**Comment by muschellij2** [comment]
It is a little hard to find, but the `...` is passed down through each function to `make_aws_call`, which has the default argument:

```r
bucket = "hcp-openaccess"
```

so you can pass this down in the `download_` functions:
```r
prefix = "HCP/100307/release-notes"
res = download_hcp_dir(
	prefix = prefix, 
	bucket = "hcp-openaccess-temp")
```
