### ISSUE TITLE
download to a user-defined folder?

### ISSUE THREAD

**Issue by jasonbian97** [muschellij2/neurohcp#6]
Hi, Thanks for the work! 
I am new to R. How can I download files to a specific folder? Where can I input the path? I tried 
```
r = download_hcp_dir("HCP/100307/T1w/Diffusion", "to/my/local/path", verbose = FALSE)
```
but it does not work.

Thanks again!

**Comment by muschellij2** [comment]
Please read the docs on function definitions.  
```r
r = download_hcp_dir("HCP/100307/T1w/Diffusion", outdir = "to/my/local/path", verbose = FALSE)
```
